services:
  - type: web
    name: telegram-stripe-bot
    env: node
    plan: free
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_GROUP_ID
        sync: false
      - key: RENDER_URL
        sync: false
      - key: WEBHOOK_SECRET_PATH
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: VERIFY_STRIPE_SIGNATURE
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PORT
        sync: false
